export const home0bj0ne = {
    lightBg: false,
    primary: true,
    imgStart: '',
    lightTopLine: true,
    lightTextDesc: true,
    buttonLabel: 'Get Started',
    description: '',
    headline: 'Adresimiz',
    lightText: true,
    topLine: 'WEB',
    img: require('../../images/restaurant.jpg'),  
    alt: 'Image',
    start: '',
};
export const home0bjTwo = {
    lightBg: true,
    primary: false,
    imgStart: 'start',
    lightTopLine: false,
    lightTextDesc: false,
    buttonLabel: 'Get Started',
    description: 'salowmalikim gowmy yagdaylrnyz otyrsynyzmy sag aman',
    headline: 'BIG.MAPS WEB DEVELOPMENT',
    lightText: false,
    topLine: 'WEB',
    img: require('../../images/ss.svg'),
    alt: 'Image',
    start: 'true',
};
export const home0bjThree = {
    lightBg: false,
    primary: true,
    imgStart: '',
    lightTopLine: true,
    lightTextDesc: true,
    buttonLabel: 'Get Started',
    description: 'salowmalikim gowmy yagdaylrnyz otyrsynyzmy sag aman',
    headline: 'BIG.MAPS WEB DEVELOPMENT',
    lightText: true,
    topLine: 'WEB',
    img: require('../../images/ss.svg'),
    alt: 'Image',
    start: '',
};
export const home0bjFour = {
    lightBg: true,
    primary: false,
    imgStart: 'start',
    lightTopLine: false,
    lightTextDesc: false,
    buttonLabel: 'Get Started',
    description: 'salowmalikim gowmy yagdaylrnyz otyrsynyzmy sag aman',
    headline: 'BIG.MAPS WEB DEVELOPMENT',
    lightText: false,
    topLine: 'WEB',
    img: require('../../images/ss.svg'),
    alt: 'Image',
    start: 'true',
};